"""Warn about units typed by hand where a shorthand macro exists.

The macro table is read from thesis.tex's \\NewDocumentCommand...\\unitvalue
lines, so a macro added there is picked up with no edit here. Flags
"511 keV" (also ~, no-space and range forms) and long-form \\qty with a
known unit; prints file:line and writes src/unit-warnings.tex for the
heading badges (no entry where clean). Warns only; never fails the build.
Run by tools/tectonic-biber.bat.
"""

import re
import sys
from pathlib import Path

from count_sentences import (
    rollup,
    strip_block_with_arg,
    strip_comments,
    walk_headings,
)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

MACRO_RE = re.compile(
    r"\\NewDocumentCommand\\(\w+)\{m\}\{\\unitvalue\{#1\}\{([^}]*)\}\}"
)
QTY_RE = re.compile(r"\\qty\{[^}]*\}\{([^}]*)\}")

# Non-prose arguments whose contents can look like units (\cite{smith2020ps}).
NON_PROSE = ("label", "cite", "ref", "eqref", "autoref", "input", "includegraphics")


def macro_table(preamble):
    """{'keV': '\\kilo\\electronvolt', ...} from the \\NewDocumentCommand lines."""
    return dict(MACRO_RE.findall(preamble))


def unit_patterns(table):
    """[(name, regex), ...] matching a hand-typed value, range included ("4-12 ns").

    Longest names first so 'keV' wins over a hypothetical 'V'.
    """
    return [
        (name, re.compile(rf"([\d.]+(?:-[\d.]+)?)\s*~?\s*{re.escape(name)}\b"))
        for name in sorted(table, key=len, reverse=True)
    ]


def scan(text, units, expansions):
    """Yield (lineno, message). Line-based: a \\topics{...} or \\cite{...}
    spanning lines slips through.
    ponytail: fine while those stay one-liners; go offset-based if they don't.
    """
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = strip_comments(raw)
        if line.lstrip().startswith("\\topics"):
            continue  # drafting scaffold, gets deleted
        for cmd in NON_PROSE:
            line = strip_block_with_arg(line, cmd)

        for name, pattern in units:
            for m in pattern.finditer(line):
                yield lineno, f"{m.group(0).strip()!r} -> \\{name}{{{m.group(1)}}}"

        for m in QTY_RE.finditer(line):
            name = expansions.get(m.group(1))
            if name:
                yield lineno, f"\\qty{{...}}{{{m.group(1)}}} -> \\{name}{{...}}"


def main():
    thesis = (SRC / "thesis.tex").read_text(encoding="utf-8")
    table = macro_table(thesis)
    if not table:
        print("check_units: no unit macros found in thesis.tex, nothing to check")
        return

    units = unit_patterns(table)
    expansions = {body: name for name, body in table.items()}

    counts, order = {}, []
    hits = 0
    for key, path, body, first_line in walk_headings():
        found = list(scan(body, units, expansions))
        for lineno, msg in found:
            # scan's lineno is body-relative; first_line anchors it in the file
            print(f"{path.relative_to(ROOT)}:{first_line + lineno - 1}: "
                  f"hand-typed unit: {msg}")
        counts[key] = len(found)
        order.append(key)
        hits += len(found)

    totals = rollup(counts, order)

    lines = ["% Generated by tools/check_units.py -- do not edit."]
    for key in order:
        if totals[key]:  # no badge where there is nothing to fix
            lines.append(
                rf"\expandafter\gdef\csname uw@{key}\endcsname{{{totals[key]}}}"
            )
    (SRC / "unit-warnings.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"check_units: {hits} hand-typed unit(s), {len(table)} macros known")


def selftest():
    table = macro_table(
        r"\NewDocumentCommand\keV{m}{\unitvalue{#1}{\kilo\electronvolt}}"
        "\n"
        r"\NewDocumentCommand\ps{m}{\unitvalue{#1}{\pico\second}}"
    )
    assert table == {"keV": r"\kilo\electronvolt", "ps": r"\pico\second"}, table

    units = unit_patterns(table)
    expansions = {b: n for n, b in table.items()}
    found = lambda s: [m for _, m in scan(s, units, expansions)]

    assert found("photons of 511 keV energy"), "plain space"
    assert found("photons of 511~keV energy"), "tilde"
    assert found("photons of 511keV energy"), "no space"
    assert found(r"\qty{10}{\pico\second}"), "long-form qty"
    assert found("a 4.5 ps window"), "decimal"
    assert found("a 4-12 ps window") == [r"'4-12 ps' -> \ps{4-12}"], "range"

    assert not found(r"the \keV{511} photon"), "macro form must pass"
    assert not found(r"% 511 keV in a comment"), "comment must pass"
    assert not found(r"\topics{511 keV scaffold}"), "topics must pass"
    assert not found(r"\cite{smith2020ps}"), "cite key must pass"
    assert not found(r"\qty{3}{\milli\metre}"), "unit with no macro must pass"
    print("check_units selftest: ok")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        sys.exit(main())
