"""Count sentences per heading in the thesis chapters.

Writes src/sentence-counts.tex, read by the document's heading badges.
Sentence heuristic: a '.' not part of a number or a common abbreviation,
after stripping comments, math, \\topics blocks and non-prose arguments.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "thesis"

ABBREVIATIONS = [
    "e.g.", "i.e.", "et al.", "vs.", "cf.", "etc.", "ca.", "approx.",
    "Fig.", "fig.", "Eq.", "eq.", "Sec.", "sec.", "Ref.", "ref.",
    "A/Prof.", "Prof.", "Dr.", "no.", "No.", "vol.", "pp.",
]

HEADING_RE = re.compile(r"\\(chapter|section|subsection)\s*(\*?)\s*(?:\[[^\]]*\])?\{")


def matching_brace(text, open_idx):
    """Index just past the brace that closes the one at open_idx."""
    depth = 0
    for i in range(open_idx, len(text)):
        if text[i] == "{" and (i == 0 or text[i - 1] != "\\"):
            depth += 1
        elif text[i] == "}" and text[i - 1] != "\\":
            depth -= 1
            if depth == 0:
                return i + 1
    return len(text)


def strip_comments(text):
    return re.sub(r"(?<!\\)%.*", "", text)


def strip_block_with_arg(text, command):
    """Remove \\command{...} including balanced braces."""
    out = []
    i = 0
    needle = "\\" + command
    while True:
        j = text.find(needle, i)
        if j < 0:
            out.append(text[i:])
            break
        out.append(text[i:j])
        k = text.find("{", j)
        if k < 0:
            break
        i = matching_brace(text, k)
    return "".join(out)


def clean_body(body):
    body = strip_block_with_arg(body, "topics")
    body = re.sub(r"\\\[.*?\\\]", " ", body, flags=re.S)   # display math
    body = re.sub(r"\$[^$]*\$", " ", body)                  # inline math
    for cmd in ("label", "cite", "ref", "eqref", "autoref", "input", "includegraphics"):
        body = strip_block_with_arg(body, cmd)
    body = re.sub(r"\\[a-zA-Z@]+\s*", " ", body)            # command names
    body = re.sub(r"[{}]", "", body)
    return body


def count_sentences(body):
    text = clean_body(body)
    for abbr in ABBREVIATIONS:
        text = text.replace(abbr, abbr.replace(".", " "))
    # a period not followed by a digit ends a sentence
    return len(re.findall(r"\.(?!\d)", text))


def chapter_paths():
    """The chapter files, in the order main.tex \\inputs them."""
    thesis = strip_comments((SRC / "main.tex").read_text(encoding="utf-8"))
    rels = re.findall(r"\\input\{(chapters/[^}]+)\}", thesis)
    return [SRC / (r if r.endswith(".tex") else r + ".tex") for r in rels]


def walk_headings():
    """Yield (key, path, body, first_line) per numbered heading, in document order.

    key is 'ch1', '1.2' or '1.2.3' -- matching the number LaTeX prints, so it
    doubles as the badge lookup key. Starred headings are skipped and do not
    advance the counters. Comments are already stripped from body.
    Shared with check_units.py; both hang badges off these keys.
    """
    ch = sec = sub = 0
    for path in chapter_paths():
        text = strip_comments(path.read_text(encoding="utf-8"))

        headings = []
        for m in HEADING_RE.finditer(text):
            end = matching_brace(text, m.end() - 1)
            headings.append((m.group(1), m.group(2) == "*", m.start(), end))

        for idx, (level, starred, _, body_start) in enumerate(headings):
            body_end = headings[idx + 1][2] if idx + 1 < len(headings) else len(text)
            if starred:
                continue
            if level == "chapter":
                ch, sec, sub = ch + 1, 0, 0
                key = f"ch{ch}"
            elif level == "section":
                sec, sub = sec + 1, 0
                key = f"{ch}.{sec}"
            else:
                sub += 1
                key = f"{ch}.{sec}.{sub}"
            first_line = text.count("\n", 0, body_start) + 1
            yield key, path, text[body_start:body_end], first_line


def rollup(counts, order):
    """Fold subsection counts into their section, and everything into its chapter."""
    totals = dict(counts)
    for key in order:
        parts = key.split(".")
        if len(parts) == 3:
            totals[f"{parts[0]}.{parts[1]}"] += counts[key]
        if not key.startswith("ch"):
            totals[f"ch{parts[0]}"] += counts[key]
    return totals


def main():
    counts, order = {}, []
    for key, _path, body, _line in walk_headings():
        counts[key] = count_sentences(body)
        order.append(key)

    totals = rollup(counts, order)

    lines = ["% Generated by tools/count_sentences.py -- do not edit."]
    for key in order:
        lines.append(rf"\expandafter\gdef\csname sc@{key}\endcsname{{{totals[key]}}}")
    (SRC / "sentence-counts.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"sentence-counts.tex: {len(order)} headings")


if __name__ == "__main__":
    main()
